tunnel: 987acd9e-e509-4260-a898-8df84e5d8c6d
credentials-file: /home/nonroot/.cloudflared/987acd9e-e509-4260-a898-8df84e5d8c6d.json

ingress:
  - hostname: myhai.org
    path: /analyst.*
    service: http://analyst-prod:5000
  - hostname: myhai.org
    service: http://backend-prod:3000
  - hostname: staging.myhai.org
    service: http://backend-staging:3000
  - service: http_status:404
