tunnel: 0ee9d91e-2b1e-4a79-9d16-4a9dd524b40b
credentials-file: /home/nonroot/.cloudflared/0ee9d91e-2b1e-4a79-9d16-4a9dd524b40b.json

ingress:
  - hostname: myhai.org
    service: http://backend:3000
  - hostname: ollama.myhai.org
    service: http://ollama-proxy:4001
  - service: http_status:404
